Return zero exit status on error

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -1,8 +1,18 @@
 #!/bin/bash
 
-set -euo pipefail
+set -eEuo pipefail
 
 DOCKER_REPO=tessereth/test-summary-buildkite-plugin
+
+on_failure() {
+    echo "Command failed with exit status: $?"
+    if [[ "$BUILDKITE_PLUGIN_TEST_SUMMARY_FAIL_ON_ERROR" != "true" ]]; then
+        echo "Suppressing failure so pipeline can continue (if you do not want this behaviour, set fail_on_error to true)"
+        exit 0
+    fi
+}
+
+trap on_failure ERR
 
 # cd to plugin directory
 cd "$( dirname "${BASH_SOURCE[0]}" )/.."
